// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woxbjjbmdkxzqusuuaat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndveGJqamJtZGt4enF1c3V1YWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0ODQ1MTIsImV4cCI6MjA4NTA2MDUxMn0.ZbJ-Jai1QsdY-oJfmDx6JKsWmSiNv7_lOFx-i1w4Etg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});